name: Build_mod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build project
        run: yarn install&& yarn run build

      - name: CommitBinaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     	
        run: |
         git config user.email "a@b.c"
         git config user.name "$GITHUB_ACTOR"
         git checkout master
         sudo git pull origin master
         sudo git add Release/iOS
         sudo git add Release/Android
         sudo git commit -m "[$GITHUB_WORKFLOW]Auto commit from Github Action"
         git remote set-url --push origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
         git push origin master		
      	
