name: Build_mod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build project
        run: |
          export CI = false
          yarn upgrade
          yarn install
          yarn run build

